"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 12:49:36.658539
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('config_overrides',
    sa.Column('section', sa.String(length=32), nullable=False),
    sa.Column('patch', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('section', name=op.f('pk_config_overrides'))
    )
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('props', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_name'), 'events', ['name'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('floors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('task_nos', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('unlock_cost', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_floors'))
    )
    op.create_table('task_types',
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('level', sa.String(length=2), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('target_seconds', sa.Integer(), nullable=False),
    sa.Column('requires_software', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('no', name=op.f('pk_task_types'))
    )
    op.create_table('theory_cards',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task_no', sa.Integer(), nullable=False),
    sa.Column('subtype_id', sa.String(length=64), nullable=True),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('code_templates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_theory_cards'))
    )
    op.create_index(op.f('ix_theory_cards_task_no'), 'theory_cards', ['task_no'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('tz', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('role_flags', sa.Integer(), nullable=False),
    sa.Column('delete_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.create_table('confidence_snapshots',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('forecast_primary', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_confidence_snapshots_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'date', name=op.f('pk_confidence_snapshots'))
    )
    op.create_table('curator_invites',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_curator_invites_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_curator_invites'))
    )
    op.create_table('curator_links',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('curator_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('access', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('invited_by', sa.BigInteger(), nullable=False),
    sa.Column('league_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_digest_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("access in ('fact','progress','full')", name=op.f('ck_curator_links_access')),
    sa.CheckConstraint("role in ('parent','tutor')", name=op.f('ck_curator_links_role')),
    sa.CheckConstraint("status in ('pending','active','revoked')", name=op.f('ck_curator_links_status')),
    sa.ForeignKeyConstraint(['curator_id'], ['users.id'], name=op.f('fk_curator_links_curator_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_curator_links_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curator_links'))
    )
    op.create_index('ix_curator_links_curator_status', 'curator_links', ['curator_id', 'status'], unique=False)
    op.create_table('daily_plans',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_plans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'date', name=op.f('pk_daily_plans'))
    )
    op.create_table('daily_stats',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('coins_earned', sa.Integer(), nullable=False),
    sa.Column('coins_capped', sa.Integer(), nullable=False),
    sa.Column('tasks_done', sa.Integer(), nullable=False),
    sa.Column('threshold_met', sa.Boolean(), nullable=False),
    sa.Column('easy_day', sa.Boolean(), nullable=False),
    sa.Column('vacation', sa.Boolean(), nullable=False),
    sa.Column('time_spent_s', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('feedback_bonuses', sa.Integer(), nullable=False),
    sa.Column('free_reveals_used', sa.Integer(), nullable=False),
    sa.Column('similar_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_stats_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'date', name=op.f('pk_daily_stats'))
    )
    op.create_table('exams',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('training', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('primary_score', sa.Integer(), nullable=True),
    sa.Column('test_score', sa.Integer(), nullable=True),
    sa.Column('per_task', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('paid_with', sa.String(length=16), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("kind in ('full','half','block')", name=op.f('ck_exams_kind')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exams_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exams'))
    )
    op.create_index(op.f('ix_exams_user_id'), 'exams', ['user_id'], unique=False)
    op.create_table('floor_trials',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('instance_ids', postgresql.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind in ('extern','boss')", name=op.f('ck_floor_trials_kind')),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], name=op.f('fk_floor_trials_floor_id_floors')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_floor_trials_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_floor_trials'))
    )
    op.create_index('ix_floor_trials_user_day', 'floor_trials', ['user_id', 'day'], unique=False)
    op.create_table('generator_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_no', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['task_no'], ['task_types.no'], name=op.f('fk_generator_versions_task_no_task_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generator_versions')),
    sa.UniqueConstraint('task_no', 'version', name='task_version')
    )
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('dedupe_key', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_notifications_dedupe_key'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('placements',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('answered', sa.Integer(), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_instance_id', sa.BigInteger(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_placements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_placements'))
    )
    op.create_table('refresh_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jti', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('skill_state',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('subtype_id', sa.String(length=64), nullable=False),
    sa.Column('task_no', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('attempts_n', sa.Integer(), nullable=False),
    sa.Column('correct_recent', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('time_ratios', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('reasons', postgresql.ARRAY(sa.String(length=16)), nullable=False),
    sa.Column('exam_results', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('last_practiced', sa.Date(), nullable=True),
    sa.Column('review_step', sa.Integer(), nullable=False),
    sa.Column('next_review', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_skill_state_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'subtype_id', name=op.f('pk_skill_state'))
    )
    op.create_index('ix_skill_state_user_review', 'skill_state', ['user_id', 'next_review'], unique=False)
    op.create_table('streaks',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('current', sa.Integer(), nullable=False),
    sa.Column('best', sa.Integer(), nullable=False),
    sa.Column('freezes', sa.Integer(), nullable=False),
    sa.Column('last_met_date', sa.Date(), nullable=True),
    sa.Column('accounted_until', sa.Date(), nullable=True),
    sa.Column('lost_on', sa.Date(), nullable=True),
    sa.Column('lost_value', sa.Integer(), nullable=False),
    sa.Column('restores_month', sa.String(length=7), nullable=False),
    sa.Column('recovered_this_month', sa.Integer(), nullable=False),
    sa.Column('frozen_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_streaks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_streaks'))
    )
    op.create_table('subtypes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task_no', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('exam_like_share', sa.Float(), nullable=False),
    sa.Column('default_difficulty', sa.Integer(), nullable=False),
    sa.Column('target_seconds', sa.Integer(), nullable=False),
    sa.Column('requires_code', sa.Boolean(), nullable=False),
    sa.Column('beta', sa.Boolean(), nullable=False),
    sa.Column('beta_until', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['task_no'], ['task_types.no'], name=op.f('fk_subtypes_task_no_task_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subtypes'))
    )
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('ref_type', sa.String(length=16), nullable=False),
    sa.Column('ref_id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_transactions_idempotency_key'))
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('user_floors',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('unlocked_by', sa.String(length=16), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state in ('locked','unlocked','boss_passed')", name=op.f('ck_user_floors_state')),
    sa.CheckConstraint("unlocked_by in ('coins','extern','placement','default','boss')", name=op.f('ck_user_floors_unlocked_by')),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], name=op.f('fk_user_floors_floor_id_floors')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_floors_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'floor_id', name=op.f('pk_user_floors'))
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('band', sa.String(length=1), nullable=False),
    sa.Column('band_pending', sa.Boolean(), nullable=False),
    sa.Column('python_level', sa.String(length=8), nullable=False),
    sa.Column('daily_time', sa.Time(), nullable=False),
    sa.Column('notifications', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('privacy_defaults', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vacation_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('easy_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('onboarding_step', sa.Integer(), nullable=False),
    sa.Column('onboarding_done', sa.Boolean(), nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('placement_done', sa.Boolean(), nullable=False),
    sa.Column('python_track_done', sa.Boolean(), nullable=False),
    sa.Column('challenge_enabled', sa.Boolean(), nullable=False),
    sa.Column('run_code_on_server', sa.Boolean(), nullable=False),
    sa.Column('show_timer', sa.Boolean(), nullable=False),
    sa.Column('cosmetics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("band in ('A','B','C')", name=op.f('ck_user_settings_band')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_settings'))
    )
    op.create_table('wallet',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('rank', sa.String(length=16), nullable=False),
    sa.Column('exam_tickets', sa.Integer(), nullable=False),
    sa.Column('free_exam_month', sa.String(length=7), nullable=False),
    sa.CheckConstraint('balance >= 0', name=op.f('ck_wallet_balance_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wallet_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_wallet'))
    )
    op.create_table('web_login_tokens',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_web_login_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_web_login_tokens'))
    )
    op.create_table('curator_focus',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.BigInteger(), nullable=False),
    sa.Column('task_nos', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['curator_links.id'], name=op.f('fk_curator_focus_link_id_curator_links'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curator_focus'))
    )
    op.create_table('instances',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('task_no', sa.Integer(), nullable=False),
    sa.Column('subtype_id', sa.String(length=64), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('hidden_seed', sa.BigInteger(), nullable=False),
    sa.Column('gen_version', sa.String(length=32), nullable=False),
    sa.Column('context', sa.String(length=16), nullable=False),
    sa.Column('slot', sa.String(length=16), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('statement_md', sa.Text(), nullable=False),
    sa.Column('assets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('answer_hash', sa.String(length=64), nullable=False),
    sa.Column('answer_kind', sa.String(length=16), nullable=False),
    sa.Column('checker', sa.String(length=32), nullable=False),
    sa.Column('checker_options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('solution_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reference_code', sa.Text(), nullable=True),
    sa.Column('method_card_id', sa.String(length=64), nullable=False),
    sa.Column('target_seconds', sa.Integer(), nullable=False),
    sa.Column('exam_like', sa.Boolean(), nullable=False),
    sa.Column('requires_code', sa.Boolean(), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('planned_for', sa.Date(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('solved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('revealed', sa.Boolean(), nullable=False),
    sa.Column('code_run_seen', sa.Boolean(), nullable=False),
    sa.Column('last_code', sa.Text(), nullable=True),
    sa.Column('draft', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exam_id', sa.BigInteger(), nullable=True),
    sa.Column('void', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state in ('planned','issued','attempted','solved','failed','revealed','expired')", name=op.f('ck_instances_state')),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_instances_exam_id_exams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_instances_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instances'))
    )
    op.create_index('ix_instances_user_planned', 'instances', ['user_id', 'planned_for'], unique=False)
    op.create_table('nudges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['curator_links.id'], name=op.f('fk_nudges_link_id_curator_links'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nudges'))
    )
    op.create_table('attempts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('answer_raw', sa.String(length=4000), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_spent_s', sa.Integer(), nullable=False),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('code_snapshot', sa.Text(), nullable=True),
    sa.Column('verify_status', sa.String(length=16), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('method_check', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("verify_status in ('n/a','pending','ok','mismatch','error','no_code')", name=op.f('ck_attempts_verify_status')),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_attempts_instance_id_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempts')),
    sa.UniqueConstraint('instance_id', 'no', name='instance_no')
    )
    op.create_index('ix_attempts_user_created', 'attempts', ['user_id', 'created_at'], unique=False)
    op.create_table('exam_answers',
    sa.Column('exam_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('task_no', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.BigInteger(), nullable=False),
    sa.Column('answer_raw', sa.String(length=4000), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('time_spent_s', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_exam_answers_exam_id_exams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_exam_answers_instance_id_instances'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exam_id', 'position', name=op.f('pk_exam_answers'))
    )
    op.create_table('issue_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolution', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_issue_reports_instance_id_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_issue_reports_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue_reports'))
    )
    op.create_table('difficulty_feedback',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.BigInteger(), nullable=True),
    sa.Column('instance_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reason_code', sa.String(length=16), nullable=False),
    sa.Column('free_text', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], name=op.f('fk_difficulty_feedback_attempt_id_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_difficulty_feedback_instance_id_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_difficulty_feedback_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_difficulty_feedback')),
    sa.UniqueConstraint('instance_id', 'user_id', name='instance_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('difficulty_feedback')
    op.drop_table('issue_reports')
    op.drop_table('exam_answers')
    op.drop_index('ix_attempts_user_created', table_name='attempts')
    op.drop_table('attempts')
    op.drop_table('nudges')
    op.drop_index('ix_instances_user_planned', table_name='instances')
    op.drop_table('instances')
    op.drop_table('curator_focus')
    op.drop_table('web_login_tokens')
    op.drop_table('wallet')
    op.drop_table('user_settings')
    op.drop_table('user_floors')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('subtypes')
    op.drop_table('streaks')
    op.drop_index('ix_skill_state_user_review', table_name='skill_state')
    op.drop_table('skill_state')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('placements')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('generator_versions')
    op.drop_index('ix_floor_trials_user_day', table_name='floor_trials')
    op.drop_table('floor_trials')
    op.drop_index(op.f('ix_exams_user_id'), table_name='exams')
    op.drop_table('exams')
    op.drop_table('daily_stats')
    op.drop_table('daily_plans')
    op.drop_index('ix_curator_links_curator_status', table_name='curator_links')
    op.drop_table('curator_links')
    op.drop_table('curator_invites')
    op.drop_table('confidence_snapshots')
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_theory_cards_task_no'), table_name='theory_cards')
    op.drop_table('theory_cards')
    op.drop_table('task_types')
    op.drop_table('floors')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_name'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    op.drop_table('config_overrides')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
